name: Python Package using Conda

on:
  push:
    paths-ignore: docs/**

jobs:
  build:
    name: test_cli (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: dss
          environment-file: env/deepss_gui.yml
          python-version: ${{ matrix.python-version }}
      - name: install libsndfile
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: sudo apt-get install libsndfile1
      - name: Conda info
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda install pytest -n dss
          conda install pytest -n base
          python -m pytest
      - name: Test cli
        shell: bash -l {0}
        run: |
          python -m dss.train --help
          xb --help
          dss-train --help
          dss-predict --help
      - name: Test cli2
        shell: bash -l {0}
        run: |
          dss-train --help
          dss-predict --help
