name: Publish to anaconda.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'manual run'

jobs:
  publish_to_anaconda:
    name: Publish to Anaconda.org
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       python-version: [3.8, 3.9, '3.10']
       os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        # https://github.com/conda-incubator/setup-miniconda
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,ncb,anaconda
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          use-mamba: true
          activate-environment: anaconda-client-env
          environment-file: build_env.yml
          condarc-file: condarc.yml

      - name: Build gui and upload to anaconda (win)
        if: runner.os == 'Windows'
        shell: cmd /C CALL {0}
        run: conda mambabuild conda/das -c conda-forge -c ncb -c anaconda -c nvidia -c numba --python ${{ matrix.python-version }} --user ncb --token %ANACONDA_TOKEN%
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          CONDA_OVERRIDE_CUDA: 11.2

      - name: Build gui and upload to anaconda (*x)
        if: runner.os != 'Windows'
        shell: bash -l {0}
        run: CONDA_OVERRIDE_CUDA=11.2 conda mambabuild conda/das -c conda-forge -c ncb -c anaconda -c nvidia -c numba --python ${{ matrix.python-version }} --user ncb --token $ANACONDA_TOKEN
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          CONDA_OVERRIDE_CUDA: 11.2
