name: Publish to anaconda.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'manual run'

jobs:
  publish_to_anaconda:
    name: Publish to Anaconda.org
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       python-version: [3.8, 3.9]  #, '3.10']
       os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        # https://github.com/conda-incubator/setup-miniconda
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,ncb,anaconda
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          use-mamba: true
#           activate-environment: anaconda-client-env
#           environment-file: build-environment.yml
#           python-version: 3.10
#           condarc-file: etc/example-condarc.yml


      - name: Build gui and upload to anaconda (win)
        if: runner.os == 'Windows'
        shell: cmd /C CALL {0}
        run: |
          conda install -y -n base -c conda-forge boa anaconda-client conda-build conda-verify & conda config --set anaconda_upload yes & conda config --set always_yes yes --set changeps1 no
          CONDA_CUDA_OVERRIDE="11.6" conda config --set anaconda_upload yes & conda mambabuild conda/das -c conda-forge -c ncb -c anaconda -c nvidia --python ${{ matrix.python-version }} --user ncb --token %ANACONDA_TOKEN%
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

      - name: Build gui and upload to anaconda (*x)
        if: runner.os != 'Windows'
        shell: bash -l {0}
        run: |
          conda install -y -n base -c conda-forge boa anaconda-client conda-build conda-verify
          conda config --set anaconda_upload yes
          conda config --set always_yes yes --set changeps1 no
          CONDA_CUDA_OVERRIDE="11.1" conda mambabuild conda/das -c conda-forge -c ncb -c anaconda -c nvidia --python ${{ matrix.python-version }} --user ncb --token $ANACONDA_TOKEN
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
